### ISSUE TITLE
Possible mismatch of the edit styles in diff_mist.py

### ISSUE THREAD

**Issue by senp98** [xavihart/Diff-Protect#3]
Thank you for your code! I found a possible mismatch problem in code Line 321-322, diff_mist.py. 
```
edit_multi_step = editor.edit_list(attack_output, restep=None, t_list=[0.01, 0.05, 0.1, 0.2, 0.3])
edit_one_step   = editor.edit_list(attack_output, restep='ddim100')
```
I think ```restep=None``` should correspond to the ```edit_one_step``` according to its implementation. Could you please check this issue?

**Comment by xavihart** [comment]
Thanks for pointing it out. I think you are right, I will check it and then fix it.

**Comment by xavihart** [comment]
the bug is fixed
